export const ALL_CALENDAR_REQUEST="ALL_CALENDAR_REQUEST";
export const ALL_CALENDAR_SUCCESS="ALL_CALENDAR_SUCCESS";
export const ALL_CALENDAR_FAIL="ALL_CALENDAR_FAIL";


export const DELETE_CALENDAR_REQUEST="DELETE_CALENDAR_REQUEST";
export const DELETE_CALENDAR_SUCCESS="DELETE_CALENDAR_SUCCESS";
export const DELETE_CALENDAR_FAIL="DELETE_CALENDAR_FAIL";
export const DELETE_CALENDAR_RESET="DELETE_CALENDAR_RESET";

export const CREATE_CALENDAR_REQUEST="CREATE_CALENDAR_REQUEST";
export const CREATE_CALENDAR_SUCCESS="CREATE_CALENDAR_SUCCESS";
export const CREATE_CALENDAR_FAIL="CREATE_CALENDAR_FAIL";
export const CREATE_CALENDAR_RESET="CREATE_CALENDAR_RESET";
export const CLEAR_ERRORS ="CLEAR_ERRORS"