export const ALL_CLIENTS_REQUEST="ALL_CLIENTS_REQUEST";
export const ALL_CLIENTS_SUCCESS="ALL_CLIENTS_SUCCESS";
export const ALL_CLIENTS_FAIL="ALL_CLIENTS_FAIL";

export const CLIENT_DETAIL_REQUEST="CLIENT_DETAIL_REQUEST";
export const CLIENT_DETAIL_SUCCESS="CLIENT_DETAIL_SUCCESS";
export const CLIENT_DETAIL_FAIL="CLIENT_DETAIL_FAIL";

export const CREATE_CLIENT_REQUEST="CREATE_CLIENT_REQUEST";
export const CREATE_CLIENT_SUCCESS="CREATE_CLIENT_SUCCESS";
export const CREATE_CLIENT_FAIL="CREATE_CLIENT_FAIL";
export const CREATE_CLIENT_RESET="CREATE_CLIENT_RESET";

export const UPDATE_CLIENT_REQUEST="UPDATE_CLIENT_REQUEST";
export const UPDATE_CLIENT_SUCCESS="UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_FAIL="UPDATE_CLIENT_FAIL";
export const UPDATE_CLIENT_RESET="UPDATE_CLIENT_RESET";


export const DELETE_CLIENT_REQUEST="DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS="DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAIL="DELETE_CLIENT_FAIL";
export const DELETE_CLIENT_RESET="DELETE_CLIENT_RESET";

export const CLEAR_ERRORS="CLEAR_ERRORS"