export const NONREQUIREDFIELDS=[
 '_id',
 "userId",
 "createdBy",
 "updatedBy",
 "__v"
]

export const FIELDS={
    //common fields (Admin /SuperAdmin Fields)
    firstname:"First Name",
    lastname:"Last Name",
    email:"Email",
    //candidate Fields
    birthdate:'Birthdate',
    status_marital:'Marital Status',
    city:'City',
    nationality:"Nationality",
    language:"Language",
    status_candidate:"Candidate Status",
    interview_done:"Interview done",
    status_info:"Status Info",
    mission_type:"Mission Type",
    sector:"Sector",
    skype:"Skype ID",
    website:"Website",
    country:"Country",
    postal_code:"Postal Code",
    canton:"Canton",
    phone:"Phone",
    mobile:"Mobile",
    street:"Street",
    car_license:"Car License",
    personal_car:"Personal Car",
    boat_license:"Boat License",
    work_permit:"Working License",
    experience:"Experience(min 3 yrs)",
    main_function:"Main Function",
    functions:"Function",
    living2:"Living",
    couple:"Couple",
    spouse_name:"Spouse Name",
    working_place:"Working Place",
    activity_rate:"Activity Rate",
    working_days:"Working Days",
    animal:"Animal",
    smoker:"Smoker",
    travel:"Travel",
    vaccine:"Vaccine",
    salary_chf:"Desired Salary",
    salary_other:"Other Salary",
    salary_13:"13th Salary",
    salary_hour:"Hourly Wage",
    certificate:"Certificate",
    feedback_ref:"Reference Feedback",
    feedback_interview:"Interview Feedback",
    infos:"More Info",
    // client Fields
    phone:"Phone",
    state:"State",
    address:"Address",
    zip_code:"Postal Code",
    city:"City",
    country:"Country",
    admin_contact:"Contact Admin",
    summary_demand:"Summary Demand",
    title_demand:"Title Demand",
    send_files:"Files Send",
    vaccine:"Vaccine",
    language:"Language",
    pa:"Personal Assistant"


}