export const ALL_ADMIN_REQUEST="ALL_ADMIN_REQUEST";
export const ALL_ADMIN_SUCCESS="ALL_ADMIN_SUCCESS";
export const ALL_ADMIN_FAIL="ALL_ADMIN_FAIL";

export const ADMIN_DETAIL_REQUEST="ADMIN_DETAIL_REQUEST";
export const ADMIN_DETAIL_SUCCESS="ADMIN_DETAIL_SUCCESS";
export const ADMIN_DETAIL_FAIL="ADMIN_DETAIL_FAIL";

export const CREATE_ADMIN_REQUEST="CREATE_ADMIN_REQUEST";
export const CREATE_ADMIN_SUCCESS="CREATE_ADMIN_SUCCESS";
export const CREATE_ADMIN_FAIL="CREATE_ADMIN_FAIL";
export const CREATE_ADMIN_RESET="CREATE_ADMIN_RESET";

export const UPDATE_ADMIN_REQUEST="UPDATE_ADMIN_REQUEST";
export const UPDATE_ADMIN_SUCCESS="UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_FAIL="UPDATE_ADMIN_FAIL";
export const UPDATE_ADMIN_RESET="UPDATE_ADMIN_RESET";



export const DELETE_ADMIN_REQUEST="DELETE_ADMIN_REQUEST";
export const DELETE_ADMIN_SUCCESS="DELETE_ADMIN_SUCCESS";
export const DELETE_ADMIN_FAIL="DELETE_ADMIN_FAIL";
export const DELETE_ADMIN_RESET="DELETE_ADMIN_RESET";

export const CLEAR_ERRORS="CLEAR_ERRORS"