export const ALL_ORDERS_REQUEST="ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS="ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL="ALL_ORDERS_FAIL";

export const UPDATE_ORDERS_REQUEST="UPDATE_ORDERS_REQUEST";
export const UPDATE_ORDERS_SUCCESS="UPDATE_ORDERS_SUCCESS";
export const UPDATE_ORDERS_FAIL="UPDATE_ORDERS_FAIL";
export const UPDATE_ORDERS_RESET="UPDATE_ORDERS_RESET";


export const DELETE_ORDERS_REQUEST="DELETE_ORDERS_REQUEST";
export const DELETE_ORDERS_SUCCESS="DELETE_ORDERS_SUCCESS";
export const DELETE_ORDERS_FAIL="DELETE_ORDERS_FAIL";
export const DELETE_ORDERS_RESET="DELETE_ORDERS_RESET";


export const CLEAR_ERRORS="CLEAR_ERRORS"