export const ALL_CANDIDATE_REQUEST="ALL_CANDIDATE_REQUEST";
export const ALL_CANDIDATE_SUCCESS="ALL_CANDIDATE_SUCCESS";
export const ALL_CANDIDATE_FAIL="ALL_CANDIDATE_FAIL";

export const CREATE_CANDIDATE_REQUEST="CREATE_CANDIDATE_REQUEST";
export const CREATE_CANDIDATE_SUCCESS="CREATE_CANDIDATE_SUCCESS";
export const CREATE_CANDIDATE_FAIL="CREATE_CANDIDATE_FAIL";
export const CREATE_CANDIDATE_RESET="CREATE_CANDIDATE_RESET";

export const CANDIDATE_DETAILS_REQUEST="CANDIDATE_DETAILS_REQUEST";
export const CANDIDATE_DETAILS_SUCCESS="CANDIDATE_DETAILS_SUCCESS";
export const CANDIDATE_DETAILS_FAIL="CANDIDATE_DETAILS_FAIL";

export const UPDATE_CANDIDATE_REQUEST="UPDATE_CANDIDATE_REQUEST";
export const UPDATE_CANDIDATE_SUCCESS="UPDATE_CANDIDATE_SUCCESS";
export const UPDATE_CANDIDATE_FAIL="UPDATE_CANDIDATE_FAIL";
export const UPDATE_CANDIDATE_RESET="UPDATE_CANDIDATE_RESET";

export const DELETE_CANDIDATE_REQUEST="DELETE_CANDIDATE_REQUEST";
export const DELETE_CANDIDATE_SUCCESS="DELETE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_FAIL="DELETE_CANDIDATE_FAIL";
export const DELETE_CANDIDATE_RESET="DELETE_CANDIDATE_RESET";

export const CLEAR_ERRORS="CLEAR_ERRORS"