export const ALL_SUPERADMIN_REQUEST="ALL_SUPERADMIN_REQUEST";
export const ALL_SUPERADMIN_SUCCESS="ALL_SUPERADMIN_SUCCESS";
export const ALL_SUPERADMIN_FAIL="ALL_SUPERADMIN_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS"